/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//     "aws_project_region": "us-west-1",
//     "aws_cloud_logic_custom": [
//         {
//             "name": "AdminQueries",
//             "endpoint": "https://w2t18kf78g.execute-api.us-west-1.amazonaws.com/dev",
//             "region": "us-west-1"
//         }
//     ],
//     "aws_cognito_identity_pool_id": "us-west-1:94447db4-b326-4a52-a376-9c8c8e3b5580",
//     "aws_cognito_region": "us-west-1",
//     "aws_user_pools_id": "us-west-1_9rxmYl1VB",
//     "aws_user_pools_web_client_id": "5mg8hh3jqpda2nsqvee9jrl7tg",
//     "oauth": {},
//     "aws_cognito_username_attributes": [
//         "EMAIL"
//     ],
//     "aws_cognito_social_providers": [],
//     "aws_cognito_signup_attributes": [
//         "EMAIL"
//     ],
//     "aws_cognito_mfa_configuration": "OFF",
//     "aws_cognito_mfa_types": [
//         "SMS"
//     ],
//     "aws_cognito_password_protection_settings": {
//         "passwordPolicyMinLength": "8",
//         "passwordPolicyCharacters": []
//     },
//     "aws_cognito_verification_mechanisms": [
//         "EMAIL"
//     ]
// };


// export default awsmobile;


/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://w2t18kf78g.execute-api.us-west-1.amazonaws.com/dev",
            "region": "us-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-west-1:94447db4-b326-4a52-a376-9c8c8e3b5580",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_xATX26JLD",
    "aws_user_pools_web_client_id": "5calh9f57ahkk6ifctcorqmh5i",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": "8",
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;

